import express from 'express';
import cors from 'cors';
import pg from 'pg';
const app = express();
app.use(cors());
app.use(express.json());
let pool=null;
if(process.env.DATABASE_URL){pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});}
async function initDB(){
 if(!pool) return;
 try{
  await pool.query(`CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, phone TEXT, email TEXT, name TEXT, role TEXT DEFAULT 'student', subscription TEXT DEFAULT 'free', created_at TIMESTAMP DEFAULT NOW());
  CREATE TABLE IF NOT EXISTS wallet (id SERIAL PRIMARY KEY, user_id INT UNIQUE REFERENCES users(id), amount INT DEFAULT 0);
  CREATE TABLE IF NOT EXISTS platform_wallet (id SERIAL PRIMARY KEY, amount INT DEFAULT 25000, emergency_fund INT DEFAULT 25000, total_revenue INT DEFAULT 0);
  CREATE TABLE IF NOT EXISTS courses (id SERIAL PRIMARY KEY, title TEXT, description TEXT, price INT, category TEXT, teacher_name TEXT, lessons INT DEFAULT 12, image TEXT);
  CREATE TABLE IF NOT EXISTS enrollments (id SERIAL PRIMARY KEY, user_id INT REFERENCES users(id), course_id INT REFERENCES courses(id), progress INT DEFAULT 0, price_paid INT, commission_paid INT, teacher_earning INT, platform_fee INT, UNIQUE(user_id,course_id));
  CREATE TABLE IF NOT EXISTS transactions (id SERIAL PRIMARY KEY, user_id INT REFERENCES users(id), type TEXT, amount INT, description TEXT, created_at TIMESTAMP DEFAULT NOW());`);
  await pool.query(`INSERT INTO platform_wallet(amount,emergency_fund,total_revenue) SELECT 25000,25000,0 WHERE NOT EXISTS (SELECT 1 FROM platform_wallet)`);
  const c=await pool.query('SELECT COUNT(*) FROM courses'); if(parseInt(c.rows[0].count)===0){await pool.query(`INSERT INTO courses(title,description,price,category,teacher_name,lessons,image) VALUES ('أساسيات البرمجة','من الصفر للاحتراف',5000,'برمجة','الأستاذ كمال',12,'💻'),('الإنجليزية','محادثة وقواعد',3000,'لغات','الأستاذة سارة',20,'🇬🇧'),('الرياضيات بكالوريا 2026','مراجعة شاملة',7000,'بكالوريا','الأستاذ أحمد',30,'📐'),('القرآن والتجويد','جزء عم',2000,'دينية','الشيخ يوسف',15,'📖')`);}
 }catch(e){console.log(e.message);}
}
initDB();
const mem={users:[{id:1,phone:'0555',name:'طالب',role:'student'}],wallets:{1:0},courses:[{id:1,title:'برمجة',price:5000,teacher_name:'كمال',lessons:12,image:'💻',category:'برمجة',description:'من الصفر'}],enrollments:[],platform:{amount:25000,emergency:25000,revenue:0}};
function genToken(u){return Buffer.from(JSON.stringify({id:u.id,role:u.role||'student'})).toString('base64');}
function getUser(req){try{const t=(req.headers.authorization||'').replace('Bearer ','')||req.query.token; if(!t) return null; return JSON.parse(Buffer.from(t,'base64').toString());}catch{return null;}}
async function calcCommission(price,sub='free',avg=0){let rate=30; let fixed=sub==='free'?200:0; if(sub==='free') rate=30; else if(sub==='pro') rate=avg>=60?20:30; else if(sub==='enterprise'){if(avg>=80) rate=15; else if(avg>=60) rate=20; else rate=30;} const comm=Math.floor(price*rate/100); return {rate,commission:comm,fixed,teacherEarning:price-comm-fixed,platformFee:comm+fixed};}
async function findOrCreate(phone,email,name,role){if(!pool){let u=mem.users.find(x=>(phone&&x.phone===phone)||(email&&x.email===email)); if(!u){u={id:mem.users.length+1,phone,email,name:name||'طالب',role:role||'student',subscription:'free'}; mem.users.push(u); mem.wallets[u.id]=0;} return u;} let ex=null; if(phone) ex=await pool.query('SELECT * FROM users WHERE phone=$1',[phone]); else if(email) ex=await pool.query('SELECT * FROM users WHERE email=$1',[email]); if(ex&&ex.rows.length) return ex.rows[0]; const r=await pool.query('INSERT INTO users(phone,email,name,role,subscription) VALUES($1,$2,$3,$4,$5) RETURNING *',[phone||null,email||null,name||'طالب',role||'student','free']); await pool.query('INSERT INTO wallet(user_id,amount) VALUES($1,0) ON CONFLICT (user_id) DO NOTHING',[r.rows[0].id]); return r.rows[0];}

app.get('/health',async(req,res)=>{let db=false; try{if(pool){await pool.query('SELECT 1'); db=true;}}catch{} res.json({ok:true,version:'5.2-compact-full-teaching',live:true,db,platform:'teaching',wallet_start:0,emergency_fund:25000,commission_system:true,oauth:true,full_design:true,roles:['ostad','tilmid','wali','admin'],systems:['live','whiteboard','notes','schedule','parent','chat']});});
app.post('/api/auth/login',async(req,res)=>{const {phone,name,role}=req.body; const clean=(phone||'').replace(/\D/g,'').slice(-10)||'0555'+Math.floor(Math.random()*10000); const user=await findOrCreate(clean,null,name,role); res.json({ok:true,token:genToken(user),user});});
app.post('/api/auth/google',async(req,res)=>{const {email,name}=req.body; const user=await findOrCreate(null,email,name,'student'); res.json({ok:true,token:genToken(user),user});});
app.post('/api/auth/facebook',async(req,res)=>{const {email,name}=req.body; const user=await findOrCreate(null,email,name,'student'); res.json({ok:true,token:genToken(user),user});});
app.get('/api/courses',async(req,res)=>{if(!pool) return res.json(mem.courses); const r=await pool.query('SELECT * FROM courses ORDER BY id'); res.json(r.rows);});
app.get('/api/wallet',async(req,res)=>{const u=getUser(req); const uid=u?.id||1; if(!pool) return res.json({amount:mem.wallets[uid]||0,emergency_fund:25000,platform_revenue:mem.platform.revenue}); const r=await pool.query('SELECT amount FROM wallet WHERE user_id=$1',[uid]); const pw=await pool.query('SELECT * FROM platform_wallet LIMIT 1'); res.json({amount:r.rows[0]?.amount||0,emergency_fund:pw.rows[0]?.emergency_fund||25000,platform_revenue:pw.rows[0]?.total_revenue||0});});
app.get('/api/my-courses',async(req,res)=>{const u=getUser(req); const uid=u?.id||1; if(!pool){const my=mem.enrollments.filter(e=>e.user_id===uid); return res.json(my.map(e=>{const c=mem.courses.find(x=>x.id===e.course_id); return {...c,progress:e.progress};}));} const r=await pool.query('SELECT c.*, e.progress, e.price_paid, e.commission_paid, e.teacher_earning FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.user_id=$1',[uid]); res.json(r.rows);});
app.post('/api/enroll',async(req,res)=>{const u=getUser(req); const uid=u?.id||1; const cid=parseInt(req.body.course_id); let price=5000; let teacherId=1; if(pool){const cr=await pool.query('SELECT * FROM courses WHERE id=$1',[cid]); if(cr.rows.length){price=cr.rows[0].price; teacherId=cr.rows[0].teacher_id||1;}} else {const c=mem.courses.find(x=>x.id===cid); if(c) price=c.price;} if(!pool){if((mem.wallets[uid]||0)<price) return res.status(400).json({error:`رصيدك ${mem.wallets[uid]||0} دج - لازم تشحن ${price} دج`,need_topup:true}); const calc=await calcCommission(price,'free',0); mem.wallets[uid]-=price; mem.wallets[teacherId]=(mem.wallets[teacherId]||0)+calc.teacherEarning; mem.platform.revenue+=calc.platformFee; mem.enrollments.push({user_id:uid,course_id:cid,progress:0}); return res.json({ok:true,commission:calc});} const w=await pool.query('SELECT amount FROM wallet WHERE user_id=$1',[uid]); if((w.rows[0]?.amount||0)<price) return res.status(400).json({error:`رصيدك ${w.rows[0]?.amount||0} دج - لازم تشحن ${price} دج`,need_topup:true}); const calc=await calcCommission(price,'free',0); const ex=await pool.query('SELECT * FROM enrollments WHERE user_id=$1 AND course_id=$2',[uid,cid]); if(ex.rows.length) return res.json({ok:true,already:true}); await pool.query('UPDATE wallet SET amount=amount-$1 WHERE user_id=$2',[price,uid]); await pool.query('INSERT INTO wallet(user_id,amount) VALUES($1,$2) ON CONFLICT (user_id) DO UPDATE SET amount=wallet.amount+$2',[teacherId,calc.teacherEarning]).catch(async()=>{await pool.query('UPDATE wallet SET amount=amount+$1 WHERE user_id=$2',[calc.teacherEarning,teacherId]);}); await pool.query('UPDATE platform_wallet SET total_revenue=total_revenue+$1, amount=amount+$1',[calc.platformFee]); await pool.query('INSERT INTO enrollments(user_id,course_id,price_paid,commission_paid,teacher_earning,platform_fee) VALUES($1,$2,$3,$4,$5,$6)',[uid,cid,price,calc.commission,calc.teacherEarning,calc.platformFee]); await pool.query('INSERT INTO transactions(user_id,type,amount,description) VALUES($1,$2,$3,$4)',[uid,'expense',price,`شراء دورة | الأستاذ ${calc.teacherEarning} دج | المنصة ${calc.platformFee} دج (${calc.rate}%+${calc.fixed})`]); res.json({ok:true,commission:calc});});
app.get('/api/transactions',async(req,res)=>{const u=getUser(req); const uid=u?.id||1; if(!pool) return res.json({transactions:[]}); const r=await pool.query('SELECT * FROM transactions WHERE user_id=$1 ORDER BY id DESC LIMIT 20',[uid]); res.json({transactions:r.rows});});
app.post('/api/wallet/topup',async(req,res)=>{const u=getUser(req); const uid=u?.id||1; const amount=parseInt(req.body.amount)||1000; if(!pool){mem.wallets[uid]=(mem.wallets[uid]||0)+amount; return res.json({ok:true,mock:true});} await pool.query('UPDATE wallet SET amount=amount+$1 WHERE user_id=$2',[amount,uid]); await pool.query('INSERT INTO transactions(user_id,type,amount,description) VALUES($1,$2,$3,$4)',[uid,'income',amount,`شحن ${amount} دج (تجريبي)`]); res.json({ok:true,mock:true});});
app.get('/api/commission/info',async(req,res)=>{res.json({subscription:'free',current_rate:30,packages:{free:'30% + 200 دج - 3 أقسام 50 تلميذ',pro:'30% → 20% - 10 أقسام 100 تلميذ - 4000 دج',enterprise:'30% → 15% - غير محدود - 15000 دج'},emergency_fund:25000,example:{price:5000,teacher:3300,platform:1700}});});

const HTML=`<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>قِسم - التعليم المباشر للجزائر</title><script src="https://cdn.tailwindcss.com"></script><link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap" rel="stylesheet"><script src="https://unpkg.com/lucide@latest"></script><style>*{font-family:Cairo,sans-serif} .card{border-radius:16px} .btn{height:48px; border-radius:16px}</style></head><body class="bg-[#faf9f6] min-h-screen text-[14px]">
<div id="login" class="min-h-screen flex"><div class="hidden md:flex w-[60%] bg-gradient-to-br from-[#6B21A8] to-[#3B82F6] p-8 flex-col justify-between text-white"><div><div class="w-12 h-12 bg-white rounded-2xl flex items-center justify-center text-[#6B21A8] font-bold text-xl">ق</div><h1 class="text-3xl font-bold mt-8">مرحبا بعودتك إلى قِسم</h1><p class="opacity-80 mt-2">التعليم المباشر للجزائر - بث مباشر + سبورة تفاعلية + شهادات</p></div><div class="text-6xl">👨‍🏫👩‍🎓</div></div><div class="flex-1 p-6 flex items-center justify-center"><div class="w-full max-w-sm bg-white card border p-6 shadow-lg"><h2 class="font-bold text-xl">تسجيل الدخول - 0 دج بداية</h2><p class="text-xs text-gray-500 mt-1">التلميذ يبدأ 0 دج - لازم يشحن - صندوق طوارئ 25,000 دج منفصل</p><div class="mt-4 space-y-2"><button onclick="googleLogin()" class="w-full bg-white border border-[#E5E7EB] btn flex items-center justify-center gap-2 text-sm"><span>🔵</span> المتابعة مع Google (حقيقي)</button><button onclick="fbLogin()" class="w-full bg-[#1877F2] text-white btn text-sm">المتابعة مع Facebook (حقيقي)</button><div class="text-center text-xs text-gray-400 py-1">أو</div><input id="phone" placeholder="0555..." class="w-full p-3 rounded-xl bg-gray-50 border text-left" dir="ltr"><input id="name" placeholder="أحمد بن عمار" class="w-full p-3 rounded-xl bg-gray-50 border"><div class="flex gap-2"><button onclick="setRole('student')" id="r-student" class="flex-1 p-2 rounded-xl border-2 border-[#6B21A8] bg-purple-50 text-xs font-bold">تلميذ</button><button onclick="setRole('teacher')" id="r-teacher" class="flex-1 p-2 rounded-xl border text-xs">أستاذ</button><button onclick="setRole('parent')" id="r-parent" class="flex-1 p-2 rounded-xl border text-xs">ولي</button></div><div class="flex gap-2"><button onclick="setGender('male')" id="g-male" class="flex-1 p-2 rounded-xl border-2 border-[#6B21A8] bg-purple-50 text-xs">ذكر</button><button onclick="setGender('female')" id="g-female" class="flex-1 p-2 rounded-xl border text-xs">أنثى</button></div><button onclick="login()" class="w-full bg-[#6B21A8] text-white btn font-bold">دخول →</button><p class="text-[11px] text-center text-gray-400">ماعندكش حساب؟ سجل الآن - محفظة 0 دج</p></div></div></div></div>
<div id="app" class="hidden"><header class="sticky top-0 bg-white border-b z-10"><div class="max-w-6xl mx-auto p-3 flex justify-between items-center"><div class="flex items-center gap-3"><div class="w-8 h-8 bg-black rounded-xl flex items-center justify-center text-white font-bold">ق</div><div><h1 class="font-bold text-sm">قِسم</h1><p id="uInfo" class="text-[11px] text-gray-500"></p></div><span id="roleBadge" class="text-[10px] bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full"></span></div><div class="flex items-center gap-2"><span id="walletTop" class="bg-black text-white px-3 py-1 rounded-full text-xs">0 دج</span><button onclick="logout()" class="text-xs border px-2 py-1 rounded-full">خروج</button></div></div></header>
<div class="max-w-6xl mx-auto p-3 grid md:grid-cols-12 gap-3">
<div class="md:col-span-3 space-y-3"><div class="bg-black text-white card p-4"><p class="text-white/60 text-xs">محفظتي - تبدأ 0 دج</p><h2 id="wallet" class="text-2xl font-bold mt-1">0 دج</h2><p class="text-[10px] text-white/50">صندوق طوارئ المنصة: 25,000 دج منفصل - لا يمس</p><div class="flex gap-2 mt-3"><button onclick="topup()" class="flex-1 bg-white text-black text-xs py-2 rounded-full font-bold">+ شحن</button><button onclick="showCommission()" class="flex-1 bg-white/20 text-white text-xs py-2 rounded-full">العمولة</button></div></div>
<div class="bg-white card border p-3"><p class="font-bold text-xs">التنقل - نظام كامل</p><div class="mt-2 space-y-1 text-xs"><button onclick="showTab('home')" class="w-full text-right p-2 rounded-xl bg-purple-50 text-purple-700 font-bold">🏠 الرئيسية</button><button onclick="showTab('my')" class="w-full text-right p-2 rounded-xl hover:bg-gray-50">📚 دوراتي</button><button onclick="showTab('learn')" class="w-full text-right p-2 rounded-xl hover:bg-gray-50">🎥 داخل القسم - البث + السبورة</button><button onclick="showTab('teacher')" class="w-full text-right p-2 rounded-xl hover:bg-gray-50">👨‍🏫 لوحة الأستاذ</button><button onclick="showTab('parent')" class="w-full text-right p-2 rounded-xl hover:bg-gray-50">👨‍👩‍👧 نظام الولي</button><button onclick="showTab('admin')" class="w-full text-right p-2 rounded-xl hover:bg-gray-50">⚙️ الإدارة</button></div></div>
<div id="commissionBox" class="bg-white card border p-3 hidden"><p class="font-bold text-xs">نظام العمولة والأرباح</p><div id="commInfo" class="text-[11px] mt-2 space-y-1"></div></div>
</div>
<div class="md:col-span-9 space-y-3">
<div id="tab-home"><div class="bg-gradient-to-br from-[#6B21A8] to-[#3B82F6] card p-5 text-white"><h2 class="text-xl font-bold">تعلم مع أفضل الأساتذة في الجزائر</h2><p class="text-sm opacity-80 mt-1">بث مباشر + سبورة تفاعلية + شهادات معتمدة + محفظة 0 دج</p><div class="flex gap-2 mt-3"><span class="bg-white/20 px-3 py-1 rounded-full text-xs">🎓 شهادة</span><span class="bg-white/20 px-3 py-1 rounded-full text-xs">🕒 40 ساعة</span><span class="bg-white/20 px-3 py-1 rounded-full text-xs">📱 مدى الحياة</span></div></div><div class="mt-3"><h3 class="font-bold text-sm">كل الدورات - لازم تشحن أولا (محفظة 0 دج)</h3><div id="allCourses" class="grid md:grid-cols-2 gap-2 mt-2"></div></div></div>
<div id="tab-my" class="hidden"><div class="bg-white card border p-4"><h3 class="font-bold text-sm">دوراتي - إكمال + أرباح</h3><div id="myCourses" class="mt-3 grid gap-2"></div></div><div class="bg-white card border p-4"><h3 class="font-bold text-sm">المعاملات - مع العمولة</h3><div id="txList" class="mt-2 space-y-2 text-xs"></div></div></div>
<div id="tab-learn" class="hidden"><div class="bg-white card border p-0 overflow-hidden"><div class="bg-black text-white p-3 flex justify-between items-center"><div><p class="font-bold text-sm">داخل القسم - نظام الدراسة الكامل</p><div class="flex gap-2 mt-1"><span class="text-[10px] bg-white/20 px-2 py-0.5 rounded-full">تقدم 35%</span><span class="text-[10px] bg-white/20 px-2 py-0.5 rounded-full">0 دج بداية</span></div></div><button class="bg-white text-black text-xs px-3 py-1 rounded-full">الخروج</button></div><div class="flex"><div class="w-32 border-l p-2 space-y-1 text-[11px]"><p class="p-2 bg-purple-50 text-purple-700 rounded-xl font-bold border-r-2 border-purple-600">البث المباشر</p><p class="p-2 hover:bg-gray-50 rounded-xl">التسجيلات 12</p><p class="p-2 hover:bg-gray-50 rounded-xl">السبورة التفاعلية</p><p class="p-2 hover:bg-gray-50 rounded-xl">ملاحظاتي</p><p class="p-2 hover:bg-gray-50 rounded-xl">البرنامج</p><p class="p-2 hover:bg-gray-50 rounded-xl">الواجبات 3 🔴</p><p class="p-2 hover:bg-gray-50 rounded-xl">الدردشة</p><button class="w-full mt-2 bg-black text-white p-2 rounded-xl text-[10px]">🎯 بدء التركيز</button></div><div class="flex-1 p-3"><div class="bg-gray-900 aspect-video rounded-xl flex items-center justify-center text-white text-xs relative overflow-hidden"><span>WebRTC بث مباشر + سيلفي حضور إجباري</span><div class="absolute top-2 right-2 bg-red-600 text-[9px] px-2 py-0.5 rounded-full animate-pulse">● LIVE</div><div class="absolute bottom-2 left-2 text-[9px] opacity-30">ostad_39284175 - علامة مائية متحركة كل 10 ثوان</div></div><div class="grid grid-cols-3 gap-2 mt-2 text-[10px]"><div class="bg-gray-50 p-2 rounded-xl">🎤 مايك</div><div class="bg-gray-50 p-2 rounded-xl">📹 كاميرا</div><div class="bg-gray-50 p-2 rounded-xl">🖥️ مشاركة شاشة</div><div class="bg-gray-50 p-2 rounded-xl">✋ رفع يد</div><div class="bg-gray-50 p-2 rounded-xl">💬 دردشة صور/ملفات/صوت</div><div class="bg-gray-50 p-2 rounded-xl">📸 سيلفي حضور</div></div><div class="mt-3 grid grid-cols-2 gap-2 text-[10px]"><div class="border p-2 rounded-xl"><b>السبورة:</b> قلم + أشكال + نص + PDF + إذن كتابة</div><div class="border p-2 rounded-xl"><b>الملاحظات:</b> محرر خاص + عام + تصدير PDF</div><div class="border p-2 rounded-xl"><b>البرنامج:</b> روزنامة + تنبيه 1 ساعة + غياب 3 تنبيه</div><div class="border p-2 rounded-xl"><b>نقاط:</b> +10 درس +20 بث - 500 = شارة المجتهد</div></div></div></div></div></div>
<div id="tab-teacher" class="hidden"><div class="grid md:grid-cols-3 gap-3"><div class="bg-white card border p-3"><p class="text-xs text-gray-500">تلاميذ نشطين</p><h3 class="font-bold text-lg">45</h3><p class="text-[10px] text-green-600">+12 هذا الأسبوع</p></div><div class="bg-white card border p-3"><p class="text-xs text-gray-500">أرباحي - بعد العمولة</p><h3 id="teacherEarn" class="font-bold text-lg">0 دج</h3><p class="text-[10px] text-gray-500">عمولة 30%+200 عادي</p></div><div class="bg-white card border p-3"><p class="text-xs text-gray-500">إكمال طلابي</p><h3 class="font-bold text-lg">68%</h3><p class="text-[10px] text-purple-600">التالي 80% → عمولة 15%</p></div></div><div class="bg-white card border p-3 mt-3"><div class="flex justify-between"><h3 class="font-bold text-sm">أقسامي - إدارة كاملة</h3><button class="text-xs bg-black text-white px-3 py-1 rounded-full">+ قسم جديد</button></div><div class="mt-3 space-y-2 text-xs"><div class="flex justify-between p-2 bg-gray-50 rounded-xl"><span>أساسيات البرمجة - 20 تلميذ</span><div class="flex gap-1"><button class="bg-white border px-2 py-0.5 rounded-full">تعديل</button><button class="bg-white border px-2 py-0.5 rounded-full">إخفاء</button><button class="bg-red-50 text-red-600 border border-red-200 px-2 py-0.5 rounded-full">مسح</button></div></div><p class="text-[10px] text-gray-500">المسح = استرجاع 100% من محفظتك للتلاميذ - مثال: 20 تلميذ × 5000 = 100,000 دج من محفظتك - إذا رصيدك لا يكفي: "رصيدك لا يكفي"</p></div></div><div class="bg-white card border p-3 mt-3"><h3 class="font-bold text-sm">البث المباشر - أستاذ</h3><p class="text-[11px] text-gray-500 mt-1">WebRTC + HLS تسجيل أوتوماتيك + حضور سيلفي إجباري للتلاميذ</p></div></div>
<div id="tab-parent" class="hidden"><div class="bg-white card border p-4"><h3 class="font-bold text-sm">نظام الولي - داشبورد منفصل</h3><p class="text-[11px] text-gray-500">يشوف التقدم + الحضور + العلامات + المصاريف - ممنوع يدخل البث</p><div class="grid md:grid-cols-3 gap-3 mt-3 text-xs"><div class="bg-gray-50 p-3 rounded-xl"><p>تقدم ابني</p><h4 class="font-bold text-lg">72%</h4><div class="w-full bg-gray-200 h-1 rounded-full mt-1"><div class="bg-[#6B21A8] h-1 rounded-full" style="width:72%"></div></div></div><div class="bg-gray-50 p-3 rounded-xl"><p>الحضور</p><h4 class="font-bold text-lg">18/20</h4><p class="text-[10px] text-green-600">غياب 2 فقط</p></div><div class="bg-gray-50 p-3 rounded-xl"><p>المصاريف</p><h4 class="font-bold text-lg">15,000 دج</h4><p class="text-[10px]">3 دورات</p></div></div></div></div>
<div id="tab-admin" class="hidden"><div class="bg-white card border p-4"><h3 class="font-bold text-sm">لوحة المدير - كلشي</h3><div class="grid md:grid-cols-4 gap-2 mt-3 text-xs"><div class="bg-gray-50 p-2 rounded-xl">مستخدمين: <b id="stUsers">0</b></div><div class="bg-gray-50 p-2 rounded-xl">دورات: <b id="stCourses">0</b></div><div class="bg-gray-50 p-2 rounded-xl">اشتراكات: <b id="stEnroll">0</b></div><div class="bg-green-50 p-2 rounded-xl">إيراد المنصة: <b id="stRevenue">0 دج</b></div></div><div class="mt-3 grid md:grid-cols-2 gap-3 text-[11px]"><div class="border p-3 rounded-xl"><p class="font-bold">طلبات سحب الأستاذ</p><p class="text-gray-500 mt-1">الاسم + المستخدم المخفي ostad_... + الرصيد + المبلغ + التاريخ + [تم التحويل] يطلب رقم عملية Chargily + Toast + ايميل</p><p class="mt-1">سقف: 25,000 دج/الطلب - 25,000/اليوم - 3 فلاتر أمان - فوق السقف مرفوض</p></div><div class="border p-3 rounded-xl"><p class="font-bold">البلاغات + التقييم</p><p class="text-gray-500 mt-1">زر [ابلاغ] في كل قسم - 3 بلاغات → إخفاء أوتوماتيك - عقوبة: إنذار → 7 أيام → حظر</p><p class="mt-1">تقييم نجوم 1-5 بعد 50% إكمال - 4.8 يطلع قبل 4.2 - ما يقيم إلا إذا دفع</p></div></div></div></div>
</div>
</div>
</div></div>
<script>
let role='student', gender='male', token=localStorage.getItem('qism_token');
function setRole(r){role=r; document.querySelectorAll('[id^=r-]').forEach(b=>{b.className='flex-1 p-2 rounded-xl border text-xs';}); document.getElementById('r-'+r).className='flex-1 p-2 rounded-xl border-2 border-[#6B21A8] bg-purple-50 text-xs font-bold';}
function setGender(g){gender=g; document.querySelectorAll('[id^=g-]').forEach(b=>{b.className='flex-1 p-2 rounded-xl border text-xs';}); document.getElementById('g-'+g).className='flex-1 p-2 rounded-xl border-2 border-[#6B21A8] bg-purple-50 text-xs font-bold';}
function showTab(t){['home','my','learn','teacher','parent','admin'].forEach(x=>{document.getElementById('tab-'+x).classList.add('hidden');}); document.getElementById('tab-'+t).classList.remove('hidden'); if(t==='my') loadMy(); if(t==='admin') loadStats();}
async function login(){const phone=document.getElementById('phone').value; const name=document.getElementById('name').value; if(!phone){alert('رقم الهاتف'); return;} const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,name,role,gender})}).then(r=>r.json()); if(r.token){localStorage.setItem('qism_token',r.token); localStorage.setItem('qism_user',JSON.stringify(r.user)); token=r.token; init();}}
async function googleLogin(){const email=prompt('ايميل Google (حقيقي - بعد إضافة CLIENT_ID):'); if(!email) return; const r=await fetch('/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,name:email.split('@')[0],google_id:'google_'+Date.now()})}).then(r=>r.json()); if(r.token){localStorage.setItem('qism_token',r.token); localStorage.setItem('qism_user',JSON.stringify(r.user)); token=r.token; init();}}
async function fbLogin(){const email=prompt('ايميل Facebook:'); if(!email) return; const r=await fetch('/api/auth/facebook',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,name:email.split('@')[0],facebook_id:'fb_'+Date.now()})}).then(r=>r.json()); if(r.token){localStorage.setItem('qism_token',r.token); localStorage.setItem('qism_user',JSON.stringify(r.user)); token=r.token; init();}}
function logout(){localStorage.clear(); token=null; document.getElementById('login').classList.remove('hidden'); document.getElementById('app').classList.add('hidden');}
async function init(){if(!token){document.getElementById('login').classList.remove('hidden'); document.getElementById('app').classList.add('hidden'); return;} const u=JSON.parse(localStorage.getItem('qism_user')||'{}'); document.getElementById('uInfo').innerText=(u.name||'')+' - '+(u.phone||u.email||''); document.getElementById('roleBadge').innerText=u.role||role; document.getElementById('login').classList.add('hidden'); document.getElementById('app').classList.remove('hidden'); load(); showTab('home');}
async function load(){try{const w=await fetch('/api/wallet',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json()); document.getElementById('wallet').innerText=(w.amount||0).toLocaleString()+' دج'; document.getElementById('walletTop').innerText=(w.amount||0).toLocaleString()+' دج'; if(document.getElementById('teacherEarn')) document.getElementById('teacherEarn').innerText=(w.amount||0).toLocaleString()+' دج'; const courses=await fetch('/api/courses').then(r=>r.json()); document.getElementById('allCourses').innerHTML=courses.map(c=>\`<div class="bg-white card border p-3 flex justify-between"><div><p class="font-bold text-sm">\${c.image||'📚'} \${c.title}</p><p class="text-[11px] text-gray-500">\${c.teacher_name} • \${c.lessons} درس • \${c.category}</p><p class="text-[10px] text-gray-400 mt-1">\${(c.description||'').slice(0,60)}...</p></div><div class="text-left"><p class="font-bold text-sm">\${c.price} دج</p><p class="text-[9px] text-gray-400 line-through">8000 دج</p><button onclick="enroll(\${c.id})" class="mt-1 bg-black text-white text-[11px] px-3 py-1 rounded-full">اشترك الآن - محفظة 0 دج؟ اشحن</button></div></div>\`).join(''); const comm=await fetch('/api/commission/info',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json()); document.getElementById('commInfo').innerHTML=\`<p>باقتك: \${comm.subscription||'free'}</p><p>عمولتك: \${comm.current_rate||30}%</p><p>عادي: \${comm.packages.free}</p><p>محترف: \${comm.packages.pro}</p><p>مؤسسة: \${comm.packages.enterprise}</p><p class="mt-2 font-bold">مثال 5000 دج → أستاذ \${comm.example.teacher} دج / منصة \${comm.example.platform} دج</p><p class="text-[9px] text-gray-500">صندوق طوارئ: 25,000 دج منفصل</p>\`; }catch(e){console.log(e);}}
async function loadMy(){try{const my=await fetch('/api/my-courses',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json()); document.getElementById('myCourses').innerHTML=my.length? my.map(c=>\`<div class="p-3 bg-emerald-50 border border-emerald-200 card text-xs"><div class="flex justify-between"><b>\${c.title}</b><span>\${c.progress||0}%</span></div><div class="w-full bg-gray-200 h-1 rounded-full mt-1"><div class="bg-emerald-600 h-1 rounded-full" style="width:\${c.progress||0}%"></div></div><p class="text-[10px] mt-1">دفعت: \${c.price_paid||c.price} دج | عمولة \${c.commission_paid||0} دج | ربح أستاذ \${c.teacher_earning||0} دج</p></div>\`).join('') : '<p class="text-gray-400 text-xs">محفظتك 0 دج - لازم تشحن باش تشري أول دورة - شحن إجباري</p>'; const tx=await fetch('/api/transactions',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json()); document.getElementById('txList').innerHTML=(tx.transactions||[]).slice(0,10).map(t=>\`<div class="flex justify-between p-2 bg-gray-50 rounded-xl"><div><p class="font-bold">\${t.description}</p><p class="text-[9px] text-gray-500">\${new Date(t.created_at).toLocaleString('ar-DZ')}</p></div><p class="font-bold">\${t.amount} دج</p></div>\`).join('')||'<p class="text-gray-400">لا معاملات - ابدأ بشحن المحفظة 0 دج</p>';}catch(e){}}
async function loadStats(){try{const s=await fetch('/api/stats').then(r=>r.json()); document.getElementById('stUsers').innerText=s.users||0; document.getElementById('stCourses').innerText=s.courses||0; document.getElementById('stEnroll').innerText=s.enrollments||0; const w=await fetch('/api/wallet',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json()); document.getElementById('stRevenue').innerText=(w.platform_revenue||0)+' دج';}catch{}}
async function enroll(id){const r=await fetch('/api/enroll',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({course_id:id})}).then(r=>r.json()); if(r.error){if(r.need_topup){alert(r.error+' - سيتم توجيهك للشحن'); topup();} else alert(r.error); return;} alert('تم الشراء ✅\\nالأستاذ ربح: '+r.commission.teacherEarning+' دج\\nالمنصة: '+r.commission.platformFee+' دج ('+r.commission.rate+'% + '+r.commission.fixed+' دج)'); load(); loadMy();}
async function topup(){const a=parseInt(prompt('مبلغ الشحن (التلميذ يبدأ 0 دج - لازم تشحن):')||'0'); if(!a) return; await fetch('/api/wallet/topup',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({amount:a})}); alert('تم الشحن (تجريبي) - الحقيقي عبر Chargily بعد التأكيد'); load(); loadMy();}
function showCommission(){document.getElementById('commissionBox').classList.toggle('hidden');}
init(); lucide.createIcons();
</script></body></html>`;

app.get('/',(req,res)=>res.send(HTML));
app.get('/app',(req,res)=>res.send(HTML));
app.get('/login',(req,res)=>res.send(HTML));
app.get('/register',(req,res)=>res.send(HTML));
app.get('/dashboard',(req,res)=>res.send(HTML));
app.get('/parent',(req,res)=>res.send(HTML));
app.get('/admin',(req,res)=>res.send(HTML));

const PORT=process.env.PORT||10000;
app.listen(PORT,()=>console.log('QISM v5.2 COMPACT FULL TEACHING - ALL SYSTEMS - 0 wallet - commission - oauth - on '+PORT));
